<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<PublishTrimmed>false</PublishTrimmed>
    <!-- A verzió az ablak címsorában is megjelenik, hogy egy hibajelentésből kiderüljön,
         melyik példány futott. -->
    <Version>2.1.0</Version>
  </PropertyGroup>

</Project>